### ISSUE TITLE
Telegram plugin does nothing

### ISSUE THREAD

**Issue by jagp8** [wpa-2/telegram.py#16]
I think I installed it properly, firste tried copying the file into the custom_plugin folder and also downloading it from the repo and in both cases executing the install.sh (but the install dependencies step last suspiciusly almost nothing)

Anyways installed the telegram bot packages with
sudo pip3 install python-telegram-bot==13.15 --break-system-packages

And when I try to execute the tele.py script (I also copied it to custom_plugins, I know there's no need but want to have it close to the plugin) it says

'''
Traceback (most recent call last):                                                                                        File "/usr/local/share/pwnagotchi/custom-plugins/tele.py", line 4, in <module>                                            import telegram                                                                                                       File "/usr/local/share/pwnagotchi/custom-plugins/telegram.py", line 13, in <module>                                       from telegram import InlineKeyboardButton, InlineKeyboardMarkup                                                     ImportError: cannot import name 'InlineKeyboardButton' from partially initialized module 'telegram' (most likely due to a circular import) (/usr/local/share/pwnagotchi/custom-plugins/telegram.py) 
'''

**Comment by wpa-2** [comment]
Did you remove the older packages first as they conflict. 
What image are you using? 
Have you made sure you edited the config file with the correct details.

**Comment by nothingbutlucas** [comment]
Hi, please try again. 
That was my bad, I was debugging the installation script and I comment the functions that remove the old packages and stuff. 
The script installation now is working.
Follow the instructions on the repo again and it should work.

**Comment by jagp8** [comment]
Yep, I removed the older packages and checked that I'm using the version 13.15 from telegram bot
The image I'm using is the one from jayofelony, pwnagotchi-bookworm
I think I edited it properly, but to tell the truth when it asks me for the chat id i don't know wich format does it expect,
https://te.me/chat_id, @chat_id or just chat_id

Ahother thing is that if I enter in python "import telegram" anywere it doent say anything, but if i do it in the custom folder project the same error appears

Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
  File "/usr/local/share/pwnagotchi/custom-plugins/telegram.py", line 13, in <module>
    from telegram import InlineKeyboardButton, InlineKeyboardMarkup
ImportError: cannot import name 'InlineKeyboardButton' from partially initialized module 'telegram' (most likely due to a circular import) (/usr/local/share/pwnagotchi/custom-plugins/telegram.py)

**Comment by jagp8** [comment]
I went to the logs and I found this

[2024-02-10 17:23:56,792] | [INFO] | [TELEGRAM] Connecting to Telegram...
[2024-02-10 17:23:57,645] | [ERROR] | Error while sending on Telegram
[2024-02-10 17:23:57,646] | [ERROR] | Chat not found

and the tele.py tool says absolutely nothing xD

**Comment by jagp8** [comment]
Ok, after further investigation I added some prints to the tele.py script to check what it was doing and it seems that it doesn't recognice the bot ID as a valid one, but if I replace the variable manually and go to the address it works

**Comment by jagp8** [comment]
Ok, it seems I wasn't using the proper chat_id, but im still geting errors I think it might be cos my bot_id contains special characters ( : and  - ) ?

**Comment by jagp8** [comment]
Yep, I tried with an old bot that has an id without - and it works with the old one

The old format of the bot id was:
000000000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
The new one is
0000000000:XXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by nothingbutlucas** [comment]
@jagp8  So.. problem solved?

**Comment by wpa-2** [comment]
> Yep, I tried with an old bot that has an id without - and it works with the old one
> 
> The old format of the bot id was: 000000000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX The new one is 0000000000:XXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXX

Sounds like its fixed for you now.

**Comment by jagp8** [comment]
I think it's more a workarround than a solution, it still fails if I go back to the bot with the - in the id

**Comment by nothingbutlucas** [comment]
Can you please share the config.toml of the telegram plugin? I use the new bot id and works fine.

**Comment by jagp8** [comment]
Hmmmmm I dont feel confortable sharing here the bot key or the chat id, but for the rest is

main.plugins.telegram.enabled = true
main.plugins.telegram.bot_token = "0000000000:XXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
main.plugins.telegram.bot_name = "Pwnagotchi"
main.plugins.telegram.chat_id = "XXXXXXX"
main.plugins.telegram.send_picture = "true"
main.plugins.telegram.send_message = "true"
main.plugins.telegram.auto_start = true

I tried to create a new bot and telegram created it without the - in the token, maybe it's just part of the random pool of characters, but when it appears the bot doesn't work

**Comment by nothingbutlucas** [comment]
Okey. The true and false values must be without "". They are true false, not strings. Same with the chatid, it's an integer, not a string.
Please, fix that and try again with the last release

**Comment by jagp8** [comment]
Ok, but those values are not the problem, cos without changing them and changing only the bot_token to the one with the - it breaks, if I put the one from another bot withoput - it works

**Comment by wpa-2** [comment]
> Ok, but those values are not the problem, cos without changing them and changing only the bot_token to the one with the - it breaks, if I put the one from another bot withoput - it works

Any updates on this, finding it hard to replicate this issue.

**Comment by wpa-2** [comment]
Will close this, feel free to open a new Issue with more information.
