### ISSUE TITLE
extra " added to certain line of config file breaking it

### ISSUE THREAD

**Issue by Kaden2003** [wpa-2/telegram.py#25]
**Describe the bug**
Through the install process (automated not manual) an extra " appears in the config, breaking the config 

**To Reproduce**
git clone https://github.com/wpa-2/telegram.py telegram-bot
cd telegram-bot
chmod 744 install.sh
./install.sh

do all of the regular setup, and for me the line "main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/" in config gets an extra " added to it like so: ""/usr/local/share/pwnagotchi/custom-plugins/""

**Image and Hardware used :**
 - Image Link: [Bookworm]
 - Image Version installed: Latest I believe
 - Hardware: 3A+

**Comment by wpa-2** [comment]
Tested and confirmed 

`main.custom_plugins = ""/usr/local/share/pwnagotchi/custom-plugins/""`

**Comment by wpa-2** [comment]
Fixed with latest comment.
