### ISSUE TITLE
install.sh disables internet connectivity

### ISSUE THREAD

**Issue by C0untZero** [wpa-2/telegram.py#29]
**Describe the bug**
I ran the install.sh script and in the middle of it I started getting the following error:
`[Errno -3] Temporary failure in name resolution`
This happened on the step below:
```
[ + ] Installing new dependencies...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
```
And after several of the warning retries it finally errors out with:
```
ERROR: Could not find a version that satisfies the requirement python-telegram-bot==13.15 (from versions: none)
ERROR: No matching distribution found for python-telegram-bot==13.15
```

Not sure if I did something wrong, this is my first attempt at this. 
Just thought it would be good to post here before reflashing the image and trying again.

**To Reproduce**
1. Run install.sh on setup as below
2. Watch it fail... ?

**Expected behavior**
The install script shouldn't disable internet connectivity in order for it to complete successfully? :)

**Image and Hardware used :**
 - Image Link: Pwnagotchi-Torch by Jayofelony
 - Image Version installed 2.8.4
 - Hardware PIzero2

**Comment by wpa-2** [comment]
I recently tested this on a new build of that image and this didn't happen, silly question but do you have internet to start? 
How did you get your internet back online? 
can you share the full output if possible.

**Comment by wpa-2** [comment]
I got this far with no errors. 

![Screenshot 2024-02-16 202601](https://github.com/wpa-2/telegram.py/assets/9049886/0abf9bb7-8d99-48eb-816f-d274f33fb436)

**Comment by nothingbutlucas** [comment]
Hi @C0untZero, please, update the repo `git pull` to the last commit and try again. I added an internet verification. So if you don't have internet, the script would do nothing.
However, the script should not do anything with your internet connection. If you see it, it does the same as the manual installation :)

**Comment by C0untZero** [comment]
Hi @nothingbutlucas , yeah actually my internet connection is intermittent for some other reason, just grabbing the latest bookworm image and reflashing now.
I saw you had some issues with torch after an auto-update, we can close this ticket and I'll create a support thread on there.

Thanks for the quick reply!
